//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "follow")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub follower_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub following_id: i32,
    pub followed_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ums_user::Entity",
        from = "Column::FollowerId",
        to = "super::ums_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UmsUser2,
    #[sea_orm(
        belongs_to = "super::ums_user::Entity",
        from = "Column::FollowingId",
        to = "super::ums_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UmsUser1,
}

impl ActiveModelBehavior for ActiveModel {}
