//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")", nullable)]
    pub content: Option<String>,
    pub author_id: i32,
    pub create_time: Option<DateTime>,
    pub update_time: Option<String>,
    pub r#abstract: Option<String>,
    pub tag_id: Option<i32>,
    pub category: Option<i32>,
    pub comment_num: Option<i32>,
    pub like_num: Option<i32>,
    pub read_num: Option<i32>,
    pub collection_num: Option<i32>,
    pub cover: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
