//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ums_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub username: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub email_verified: i8,
    pub nickname: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar: Option<String>,
    pub gender: Option<String>,
    pub birthday: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub background_image: Option<String>,
    pub password: Option<String>,
    pub home_page: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub score: i32,
    pub status: i32,
    pub topic_count: i32,
    pub comment_count: i32,
    pub follow_count: i32,
    pub fans_count: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub roles: Option<String>,
    pub forbidden_end_time: i64,
    pub create_time: Option<i64>,
    pub update_time: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
